### ISSUE TITLE
keep loading...

### ISSUE THREAD

**Issue by aemaddin** [dcasia/nova-filepond#1]
added the package to nova then put this at posts resources
`
Filepond::make('Image')
                ->disk('public', 'posts')
                ->creationRules('required')
                ->withoutDoka(),
`

the result is keep loading forever

<img width="509" alt="Screen Shot 2019-10-03 at 11 38 05 AM" src="https://user-images.githubusercontent.com/11630742/66116140-8217c700-e5d2-11e9-82ff-722bc31b1090.png">

My Dev Env :-

Laravel 5.8.35
Nova 2.4.0
php 7.3.9

**Comment by milewski** [comment]
Hi @aemaddin , problem fixed on version `v0.2.1`

**Comment by aemaddin** [comment]
👍 

Many thanks.
