### ISSUE TITLE
Use of storeOriginalName

### ISSUE THREAD

**Issue by vayurobins** [dcasia/nova-filepond#10]
Hi.
Is it not possible to use the builtin functions, that the File Field has in Nova?
https://nova.laravel.com/docs/2.0/resources/file-fields.html#storing-metadata
For instance, is it not possible to use storeOriginalName()?

By the way, this extension is really good, thanks for sharing!

**Comment by naifalshaye** [comment]
use Illuminate\Http\File instead of use Laravel\Nova\Fields\File

**Comment by milewski** [comment]
@naifalshaye what are you talking about?

**Comment by naifalshaye** [comment]
@milewski  How I'm supposed to use storeOriginalName() method in  Nova File Field?

**Comment by milewski** [comment]
@naifalshaye see my reply to this PR https://github.com/dcasia/nova-filepond/pull/13, you can use it meanwhile I still havent complete the rework for v2

**Comment by danmatthews** [comment]
Any word on when this might become available? I've used this package in a piece of work, but it's no good unless I can store the original filename too.

Great package btw.

**Comment by milewski** [comment]
Unfortunately, I still haven't got time to finish it :( I faced some issues with the package especially allowing multiple files upload... that's trouble there were too many cases to handle..

**Comment by vayurobins** [comment]
I think it should be possible to store files with original name like this. I have not tested this, but I think it could work until storeOriginalName() is added. Please correct me if I'm wrong.
```
Filepond::make(__('Invoices'), 'invoices')->storeAs(function (File $file) {
    return $file->getClientOriginalName() . '.' . $file->getExtension();
})
```

**Comment by milewski** [comment]
the `File` is not the real uploaded file object but a mock I create, the original information from the UploadedFile object is lost, this PR #13 adds it to a temp json file and retrieve it back when the user clicks save, not idea solution, my rewrite I was encoding all these missing information directly into the serverid that is transferred between the requests... but I think I won't have time to finish it so  soon

**Comment by danmatthews** [comment]
Ok Cool, i might have to fork the package and use this pull request then, as i really need this functionality. Thanks for all the work you've put in on it so far!

**Comment by milewski** [comment]
Hi latest version supports nova 4 and fixes a lot of issues, now you can store original name + anything else you would like the same way you can do with the native nova file field: [v1.0.0](https://github.com/dcasia/nova-filepond/releases/tag/v1.0.0)
