### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by glebihan** [dcasia/nova-filepond#12]
Would it be possible to allow all filepond texts to be localized ?
Currently, only labelIdle is localized when instantiating the FilePond instance.

Thanks.

**Comment by vayurobins** [comment]
I would also like to be able to change the text, ex: "Drop Files here..."

**Comment by milewski** [comment]
Hi you can now translate everything from the config file: [v0.2.13](https://github.com/dcasia/nova-filepond/releases/tag/v0.2.13)

**Comment by glebihan** [comment]
Thanks !

**Comment by NoahNxT** [comment]
Hi,
is there a way to use translations from a translation json instead of hardcoded ones in the config? We have a multi-language nova site and we would like to use multiple translations.
