### ISSUE TITLE
ErrorException: tempnam(): file created in the system's temporary directory

### ISSUE THREAD

**Issue by hasnatbabur** [dcasia/nova-filepond#16]
Getting "ErrorException: tempnam(): file created in the system's temporary directory" after dropping file in filepond area. I am on windows 10 and using Laragon server with php 7.4.1.

package FilepondController.php line 62
```
$tempPath = '/tmp';
$filePath = tempnam($tempPath, 'nova-filepond-');
```

It will be best if you use sys_get_temp_dir() function instead of hardcoded '/tmp' folder. 
Or using '@' symbol to ignore warning in windows 10. Thanks

Please also see same issue here Sopamo/laravel-filepond#5

Please help. Thanks

**Comment by milewski** [comment]
Can you try modifying your local file with your suggestion, and see if it does fix this problem? If it does I can quickly submit a PR

**Comment by hasnatbabur** [comment]
This is an issue for windows machine for php /tmp path. Developing in docker container does not have this issue. Thanks
