### ISSUE TITLE
Invalid encrypted file path response when using laravel-debugbar library

### ISSUE THREAD

**Issue by hasnatbabur** [dcasia/nova-filepond#17]
Please have a look at the response, laravel-debugbar library scripts are appended in encrypted file path response. Windows 10, php 7.4.1.

Perhaps setting xmlhttprequest in header while uploading file may solve the problem.

Please see here:
https://github.com/barryvdh/laravel-debugbar/issues/734

![Capture](https://user-images.githubusercontent.com/7908425/74091208-51dfb800-4adf-11ea-9341-a5a78634ec34.PNG)

Thanks

**Comment by hasnatbabur** [comment]
solved by excluding filepond path in laravel-debugbar config

**Comment by bayhasdev** [comment]
can i ask what filepond  path to exclude

**Comment by hasnat-we** [comment]
@bayhasdev The filepond route paths you use. I set following in the bedugbar config file:

```
    'enabled' => env('DEBUGBAR_ENABLED', false),
    'except' => [
        'horizon*',
        'telescope*',
        'filepond*',
        'nova-vendor/nova-filepond*',
        'nova-vendor/nova-ck-editor*'
    ],
```
Notice the 'filepond*', I hope this will help.
