### ISSUE TITLE
Uploading file 404 process

### ISSUE THREAD

**Issue by dacastro4** [dcasia/nova-filepond#18]
Hey. I recently installed this package but every time I try to upload any type of file I get a 404.
It says that `/nova-vendor/nova-filepond/process` doesn't exist. I check the code for it and I see it, I also see it in the `route:list`. You have any idea why this could be happening? It doesn't happen with anything else but this call and the `/load` works fine.

**Comment by milewski** [comment]
Perhaps its because it failed to create a temp file on your system? https://github.com/dcasia/nova-filepond/issues/16

**Comment by dacastro4** [comment]
Which temp file? I don't think I'm aware of it

**Comment by milewski** [comment]
Try changing:

https://github.com/dcasia/nova-filepond/blob/master/src/Http/Controllers/FilepondController.php#L61

 `/tmp` to `sys_get_temp_dir()` if this works for you I can submit a PR with this change

**Comment by dacastro4** [comment]
I just check what you mention but I don't think it has anything to do with that because it's not even reaching the controller. It's returning a 404 meaning, it's not finding the route for some reason

**Comment by milewski** [comment]
It's possible that something inside that method is throwing a not found error and that's why you see a 404, I suggest you add a dd() on the very first line of the process method and see if this is the case.

**Comment by dacastro4** [comment]
I found the issue. I fixed it on my forked repo but I'm going to create a PR so you can see the changes and take something out of it if you want.
