### ISSUE TITLE
Disable encrypting file path/url

### ISSUE THREAD

**Issue by hasnatbabur** [dcasia/nova-filepond#22]
We are using AWS S3. S3 is public. So see if there is an option to disable encrypting file path/url. So we will upload files directly to S3, and while viewing S3 file we want to load them by direct S3 public object url.

So this will reduce load on PHP side, as we feel PHP can have much overhead if it handles lots of encrypted file loading routes. 
So can the encryption part and checking if real system temp  path can be disabled on demand? Thanks

I am not sure about the security issues we may face because of the request. Can one see secret files if he changes filepath manually in filepond instance from browser? Thanks

**Comment by milewski** [comment]
Hi encryption is a necessary step of the process you can read the process flow on the filepond website: https://pqina.nl/filepond/docs/api/server/#process
