### ISSUE TITLE
Save the file in the relation table

### ISSUE THREAD

**Issue by gmarineau** [dcasia/nova-filepond#28]
Hi,

Thank for the works ! It's great.

I just try to work with this package spatie/media-library.

Do you any idea how to proceed ?

Best regards

**Comment by milewski** [comment]
Hi, latest version now allows you to customize how you store the data in the database the same way the default Nova file field works: [v1.0.0](https://github.com/dcasia/nova-filepond/releases/tag/v1.0.0)
