### ISSUE TITLE
Use cloud storage(S3 or OSS) wrong

### ISSUE THREAD

**Issue by imnpc** [dcasia/nova-filepond#34]
Laravel 10
Nova 4.27.14

after uploading image, save and edit,
can't load the uploaded image from cloud storage(S3 or OSS).
if use local disk,it will work ok.

![WX20231012-143510@2x](https://github.com/dcasia/nova-filepond/assets/5801647/59497bdb-8c74-48b7-958a-c3dd872ff98f)

```php
Filepond::make(__('pictures'),'pictures')
              ->multiple()
              ->allowReorder()
              ->disk(config('filesystems.default'))
              ->path('goods/pictures/'. date('Y/m/d')) // 图片存储路径
              ->image(),
```

**Comment by milewski** [comment]
Hao le, xianzai keyi yong [v1.0.1](https://github.com/dcasia/nova-filepond/releases/tag/v1.0.1)

**Comment by imnpc** [comment]
Now work ok
Thanks!
