### ISSUE TITLE
Original name doesn't show

### ISSUE THREAD

**Issue by Keko-94** [dcasia/nova-filepond#43]
Hello,

When I use disablePreview() the original file name appears but if I don't use it, the stored file name is used.

**Comment by Keko-94** [comment]
I modified the LoadController like this and it seems to work.

return Storage::disk($data->disk)->response($data->path, **$data->filename**);

**Comment by milewski** [comment]
Thanks released it as [v1.0.5](https://github.com/dcasia/nova-filepond/releases/tag/v1.0.5)
