### ISSUE TITLE
trimSlashes problem after Upgrade to nova 2.5

### ISSUE THREAD

**Issue by Crazymodder** [dcasia/nova-filepond#5]
Hi,

After upgrading to Nova 2.5 I got this error:

`Argument 1 passed to DigitalCreative\Filepond\Filepond::trimSlashes() must be of the type string, null given, called in /var/www/vendor/digital-creative/nova-filepond/src/Filepond.php on line 160`

Thats how I implement Fielpond in my Nova Ressource

`Filepond::make(__('product.image.title'), 'image')
                ->help(__('product.image.help'))
                ->mimesTypes(['image/jpeg', 'image/jpg', 'image/gif', 'image/png'])
                ->disk('public')
                ->storeAs(function (File $file) {
                    return Str::random(13) . '.' . $file->getExtension();
                }),`

**Comment by milewski** [comment]
@Crazymodder Fixed on version `v0.2.7`
