### ISSUE TITLE
Doka included?

### ISSUE THREAD

**Issue by rikschennink** [dcasia/nova-filepond#7]
Awesome you created this package! 🙌

I'm not a 100% sure but from the readme it's unclear if Doka is included in the package. Maybe it's a good idea to make it more explicit that this is a commercial product and that the developer should purchase a license and has to manually add the required files.

**Comment by milewski** [comment]
> I'm not a 100% sure but from the readme it's unclear if Doka is included in the package.

Surely it's not included 😆  

But yeah reading the doc again I have assumed that description of js_path/css_path would be enough to figure that out that they should include the required files ... but didn't realize people might not know its a paid plugin 

```php
doka' => [
    'enabled' => true,
    'js_path' => public_path('doka.min.js'), // this assumes you places theses files within your public directory
    'css_path' => public_path('doka.min.css'),
]
```

If you could update that readme with some official wording of your product that would be awesome

**Comment by rikschennink** [comment]
@milewski I suspected it wasn't but still thanks for confirming :D

I'll see if I can add some words to the readme. 👍

**Comment by rikschennink** [comment]
Done!

**Comment by milewski** [comment]
Thanks! merged!
