### ISSUE TITLE
hi . I have the problem?

### ISSUE THREAD

**Issue by phamducthinhdev** [dcasia/nova-filepond#9]
<img width="582" alt="Screen Shot 2019-10-24 at 4 09 28 PM" src="https://user-images.githubusercontent.com/27260441/67470922-c00b8680-f678-11e9-8313-9b52e3609ae5.png">

**Comment by milewski** [comment]
@phamducthinhdev isnt this because you dont have nova installed?

**Comment by milewski** [comment]
Solved? Let me know if it's a issue.
